### ISSUE TITLE
deploy error :( how to fix

### ISSUE THREAD

**Issue by gariox3d** [bagussatoto/info-wedding#12]
error during build:
Error: Unable to parse HTML; 23
 at {"file":"/vercel/path0/index.html","line":26,"column":3}
24 |      <div id="app"></div>
25 |      <script type="module" src="/src/main.js"></script>
26 |    </body>
   |    ^
27 |  </html>
28 |  
    at handleParseError (/vercel/path0/node_modules/vite/dist/node/chunks/dep-88bd5805.js:29103:11)
    at traverseHtml (/vercel/path0/node_modules/vite/dist/node/chunks/dep-88bd5805.js:29059:9)
    at async Object.transform (/vercel/path0/node_modules/vite/dist/node/chunks/dep-88bd5805.js:29136:17)
    at async transform (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:22049:16)
    at async ModuleLoader.addModuleSource (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:22275:30)
Error: Command "npm run build" exited with 1

**Comment by webbrain-one** [comment]
Hi there! 👋 Thanks for flagging this. I've opened a pull request to fix the deploy error: https://github.com/bagussatoto/info-wedding/pull/170. The build was failing because of a missing opening `<body>` tag in `index.html`, which caused Vite's HTML parser to throw an error at line 26. The PR adds the missing tag to properly structure the document, which should resolve the build failure and get your deploy working again. Let me know if you have any questions or if it needs adjustments! 🚀
